lojavirtual_v2/blog/urls.py
from django.urls import path, re_path, include
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.BlogIndex.as_view(), name='index'),
    path('posts', views.PostList.as_view(), name='lista_post'),
    re_path(r'^post/(?P<pk>[0-9]+)$', views.BlogDetail.as_view(), name='post'),
    re_path(r'^post/(?P<pk>[0-9]+)/comentario$', views.comentario_novo, name="comentario_novo"),
    re_path(r'^comentario/(?P<pk>[0-9]+)/like$', views.comentario_like, name="comentario_like"),
    re_path(r'^comentario/(?P<pk>[0-9]+)/unlike$', views.comentario_unlike, name="comentario_unlike"),
]

lojavirtual_v2/lojavirtual/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    ##path('', include ('pages.urls')),
    ##path("cart/", include("cart.urls")),
    ##path("blog/", include("blog.urls")),
    path('', include ('products.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

lojavirtual_v2/products/urls.py
from django.urls import path, re_path

from .views import ProductDetailView, ProductListView, ProductHomeView, SaleListView, comentario_novo

app_name = "products"

urlpatterns = [
    path("", ProductHomeView.as_view(), name="home"),
    path("list", ProductListView.as_view(), name="list"),
    path("list/<slug:slug>/", ProductDetailView.as_view(), name="detail"),
    path("category/<slug:slug>/", ProductListView.as_view(), name="list_by_category"),
    path("sale/<slug:slug>/", SaleListView.as_view(), name="list_by_sale"),
    re_path(r'^list/(?P<pk>[0-9]+)/comentario$', comentario_novo, name="comentario_novo"),
]

lojavirtual_v2/templates/about.html
{% extends 'base.html' %}

{% block title %}Sobre Nós{% endblock title %}

{% block content %}

<div class="container my-3">
    <h1 class="font-weight-bold">Sobre nós</h1>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, totam iure numquam quaerat amet, officiis
        accusantium dolor assumenda dolores esse dignissimos voluptatem. Commodi laborum non minima dolor illum
        reiciendis est.Temporibus delectus quam odit voluptatibus debitis nesciunt optio voluptates ut inventore porro
        perferendis, quidem magnam repellat quo ratione, quos quod? Nesciunt, in quidem. Necessitatibus sapiente ad iure
        impedit quod cumque?
    </p>
    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur laborum nam aliquid nostrum a omnis temporibus
        deserunt fugit similique quod? Aliquam, eius quos quam laudantium ea deserunt consectetur magnam
        soluta.Accusamus enim fugit voluptatem, quasi, labore tempora adipisci magni ea voluptatum culpa recusandae qui
        reiciendis maiores ratione animi velit corrupti sequi ab eum placeat. Voluptatem quaerat nesciunt reiciendis
        aperiam vero.
    </p>
</div>

{% endblock content %}

lojavirtual_v2/templates/base.html
<!DOCTYPE html>
<html lang="pt-BR">

{% load static %}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" 
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <!-- Folhas de estilo -->
    <!--link rel="stylesheet" href="{% static 'css/style.css' %}" /-->
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
    {% block css %}{% endblock css %}
    <title>LusArtes {% block title %}{% endblock title %}</title>
</head>

<body class="d-flex flex-column min-vh-100">
    <!--header-->
    <div class="logo">
        <div class="row banner">
            <!--div class="col-sm-2 logo">
                <img src="{% static 'images/logo0002.png' %}" alt="Lu's Artes">
            </div-->
            <div class="col-sm logo">
                <img src="{% static 'images/logo001.png' %}" alt="Lu's Artes">
            </div>
            <!--div class="col-sm-2 logo">
            </div-->
        </div>
    </div>
    <!--/header-->

    <nav class="navbar navbar-expand-lg navbar-light estilo-nav">
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/logo001.png' %}"  height="30" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <!--li class="nav-item {% if request.path ==  '/products/' %} active {%endif%}">
                    <a class="nav-link" href="{% url 'products:home' %}">Home <span class="sr-only">(current)</span></a>
                </li-->
                <li class="nav-item {% if request.path ==  '/products/' %} active {%endif%}">
                    <a class="nav-link" href="{% url 'products:home' %}">Novidades</a>
                </li>
                {% for cat in categories %}
                <li class="nav-item {% if request.path ==  cat.get_absolute_url  %} active {%endif%}">
                <a class="nav-link" href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
                </li>
                {% endfor %}
                <li class="nav-item {% if request.path ==  '/products/list' %} active {%endif%}">
                    <a class="nav-link" href="{% url 'products:list' %}">Todas as categorias</a>
                </li>
               
            </ul>
            <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'products:list' %}">
                <input class="form-control mr-sm-2" type="search" name="procurar" placeholder="Pesquisar" aria-label="Search" value="{{ request.GET.search }}">
                <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">
                      <i class="bi-search" role="img" aria-label="Search"></i>
                </button>
            </form>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}
    <footer class="blog-footer">     
        <p>
          <a href="#"><img src="{% static 'images/logo001.png' %}" alt="Lu's Artes" style="width: 10%;"></a>
        </p>
        <i class="bi bi-mailbox"> comercial@lusartes.com.br</i>

      </footer>

   <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" 
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" 
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" 
        crossorigin="anonymous"></script>

    <!-- script personalizados-->
    {% block scripts %}
    {% endblock scripts %}

</body>

</html>

lojavirtual_v2/templates/home.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-3">
    <h1 class="font-weight-bold">Olá!</h1>
    <p>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur autem beatae saepe at nulla accusamus,
        mollitia quibusdam laborum, voluptatem corporis molestiae ipsa, id quasi distinctio deserunt et. Ipsam, dolorem
        quidem.Itaque, magnam explicabo! Corrupti eos optio repellat debitis omnis voluptates laudantium fuga dolore
        incidunt autem. Veritatis harum sunt eveniet sequi, impedit quaerat modi assumenda recusandae molestias adipisci
        laborum cumque ad.
    </p>
    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid non porro temporibus, unde pariatur sit
        doloremque molestiae fugit, nostrum, atque beatae praesentium vero deserunt aspernatur cumque culpa reiciendis
        corrupti dolores!Illum ratione enim repellendus quas? Inventore at aut aliquid minus pariatur facilis id
        adipisci consequuntur soluta doloremque. Sit quae quisquam quis molestiae similique esse natus atque saepe rem
        placeat? Nostrum?
    </p>
</div>

{% endblock content %}

lojavirtual_v2/templates/pagination.html
<div>
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Anterior</a>
    {% endif %}
    Página {{ page.number }} de {{ page.paginator.num_pages }}.
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Próxima</a>
    {% endif %}
</div>