lojavirtual_v2/blog/urls.py
from django.urls import path, re_path, include
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.BlogIndex.as_view(), name='index'),
    path('posts', views.PostList.as_view(), name='lista_post'),
    re_path(r'^post/(?P<pk>[0-9]+)$', views.BlogDetail.as_view(), name='post'),
    re_path(r'^post/(?P<pk>[0-9]+)/comentario$', views.comentario_novo, name="comentario_novo"),
    re_path(r'^comentario/(?P<pk>[0-9]+)/like$', views.comentario_like, name="comentario_like"),
    re_path(r'^comentario/(?P<pk>[0-9]+)/unlike$', views.comentario_unlike, name="comentario_unlike"),
]

lojavirtual_v2/lojavirtual/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    ##path('', include ('pages.urls')),
    ##path("cart/", include("cart.urls")),
    ##path("blog/", include("blog.urls")),
    path('', include ('products.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

lojavirtual_v2/blog/models.py
from django.db import models
from marcador import models as app_marcador
from django.conf import settings

# Create your models here.
class Post (models.Model):
    titulo = models.CharField(max_length=200)
    texto = models.TextField()
    publicado = models.BooleanField(default=False)
    data_criado = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, null=True)
    link_media = models.CharField(max_length=300, null=True, blank=True)
    image = models.ImageField(upload_to="blog/%Y/%m/%d", blank=True)

    def __str__ (self):
        return self.titulo

class Comentario (models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    autor = models.CharField(max_length=100)
    texto = models.TextField()
    likes = models.IntegerField(default=0)
    unlikes = models.IntegerField(default=0)
    data_criado = models.DateTimeField(auto_now_add=True)

    def __str__ (self):
        return self.autor + " - " + str (id)

    def like (self):
        self.likes += 1

    def unlike (self):
        self.unlikes += 1

class Post_Marcador(models.Model):
    marcador = models.ForeignKey(
        app_marcador.Marcador, related_name="post_marcadors", on_delete=models.CASCADE
    )
    ppost = models.ForeignKey('Post', on_delete=models.CASCADE)
    

lojavirtual_v2/products/models.py
from autoslug import AutoSlugField #instalado de terceiros
from marcador import models as app_marcador
from django.db import models
from django.urls import reverse
from model_utils.models import TimeStampedModel #instalado de terceiros (cria data de criação em alteração)


class AvailableManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_available=True)

class Category(TimeStampedModel):
    name = models.CharField(max_length=255, unique=True)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="name") #
    image = models.ImageField(upload_to="category/%Y/%m/%d", blank=True, null=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'categoria' 
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("products:list_by_category", kwargs={"slug": self.slug})


class Product(TimeStampedModel):
    category = models.ForeignKey(
        Category, related_name="products", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=255)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="name")
    image = models.ImageField(upload_to="products/%Y/%m/%d", blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    is_available = models.BooleanField(default=True)
    link_venda = models.CharField(max_length=300, null=True, blank=True)
    nota = models.IntegerField (default=0)
    likes = models.IntegerField(default=0)

    objects = models.Manager()
    available = AvailableManager()

    class Meta:
        ordering = ("-created",)
        verbose_name = 'produto'
        verbose_name_plural = 'produtos'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("products:detail", kwargs={"slug": self.slug})     

    def like (self):
        self.likes += 1  

class Comentario(TimeStampedModel):
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    autor = models.CharField(max_length=100)
    texto = models.TextField()
    likes = models.IntegerField(default=0)
    unlikes = models.IntegerField(default=0)
    data_criado = models.DateTimeField(auto_now_add=True)
    is_available = models.BooleanField(default=False)
    
    objects = models.Manager()
    available = AvailableManager()

    class Meta:
        ordering = ("-data_criado",)

    def __str__ (self):
        return self.autor + " - " + str (id)

    def like (self):
        self.likes += 1

    def unlike (self):
        self.unlikes += 1


class Images(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/%Y/%m/%d", blank=True)

    class Meta:
        verbose_name = 'imagem'
        verbose_name_plural = 'imagens'

class Sale(TimeStampedModel):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="name")
    image = models.ImageField(upload_to="sales/%Y/%m/%d", blank=True)
    is_available = models.BooleanField(default=True)

    objects = models.Manager()
    available = AvailableManager()

    class Meta:
        ordering = ('-created',)
        verbose_name = 'promoção' 
        verbose_name_plural = 'promoções'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("products:list", kwargs={"slug": self.slug})  

class Sale_Product(models.Model):
    sale = models.ForeignKey('Sale', on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    objects = models.Manager()

    class Meta:
        verbose_name = 'produtos por promoção'

class Product_Marcador(models.Model):
    marcador = models.ForeignKey(
        app_marcador.Marcador, related_name="product_marcadors", on_delete=models.CASCADE
    )
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    objects = models.Manager()

    class Meta:
        verbose_name = 'produtos por marcador'

lojavirtual_v2/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import HttpResponse
from django.views.generic import DetailView, ListView, TemplateView
from .models import Post, Comentario
from .forms import ComentarioForm

# Create your views here.
#def BlogIndex (request):
#    return render (request, 'home.html')
class BlogIndex (TemplateView):
    template_name = "blog/post_destaques.html"
    def get_context_data(self, **kwargs):    
        context = super().get_context_data(**kwargs)
        context['destaque_list'] = Post.objects.all()[:3]
        return context

class PostList (ListView):
    paginate_by = 3
    def get_queryset(self):
        queryset = Post.objects.all()
        busca = self.request.GET.get("procurar")
        if busca:
            queryset = queryset.filter(titulo__icontains = busca)
        return queryset

class BlogDetail (DetailView):
    model = Post
    

def comentario_novo (request, pk):
    post = get_object_or_404 (Post, pk=pk)
    if request.method == 'POST':
        form = ComentarioForm (request.POST)
        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.post = post
            comentario.save()
            return redirect (reverse ('blog:post', kwargs={'pk': post.pk}))
    else:
        form = ComentarioForm()
    return render (request, 'blog/comentario.html', {'form': form})

def comentario_like(request, pk):
    comentario = get_object_or_404 (Comentario, pk=pk)
    comentario.like()
    comentario.save()
    return redirect (reverse ('blog:post', kwargs={'pk': comentario.post_id}))

def comentario_unlike(request, pk):
    comentario = get_object_or_404 (Comentario, pk=pk)
    comentario.unlike()
    comentario.save()
    return redirect (reverse ('blog:post', kwargs={'pk': comentario.post_id}))

lojavirtual_v2/templates/blog/base_blog.html
{% extends "base.html" %}

{% load static %}

{% block css %}
<!--link rel="stylesheet" href="{% static 'css/style_blog.css' %}" /-->
<link rel="stylesheet" href="{% static 'css/blog.css' %}">
{% endblock css %}

{% block content %}
<main class="container"> 
  
  {% block blog_destaques %} 
  {% endblock blog_destaques %}
  

  <div class="row">
    <div class="col-md-8" style="margin-top: 2rem;">
      {% block post_entries %} 
      {% endblock post_entries %}
    </div>

    <div class="col-md-4" style="margin-top: 2rem;">
      <div class="p-4 mb-3 bg-light rounded">
        <h4 class="fst-italic">About</h4>
        <p class="mb-0">Saw you downtown singing the Blues. Watch you circle the drain. Why don't you let me stop by? Heavy is the head that <em>wears the crown</em>. Yes, we make angels cry, raining down on earth from up above.</p>
      </div>

      <div class="p-4">
        <h4 class="fst-italic">Archives</h4>
        <ol class="list-unstyled mb-0">
          <li><a href="#">March 2014</a></li>
          <li><a href="#">February 2014</a></li>
          <li><a href="#">January 2014</a></li>
          <li><a href="#">December 2013</a></li>
          <li><a href="#">November 2013</a></li>
          <li><a href="#">October 2013</a></li>
          <li><a href="#">September 2013</a></li>
          <li><a href="#">August 2013</a></li>
          <li><a href="#">July 2013</a></li>
          <li><a href="#">June 2013</a></li>
          <li><a href="#">May 2013</a></li>
          <li><a href="#">April 2013</a></li>
        </ol>
      </div>

      <div class="p-4">
        <h4 class="font-italic">Também estamos</h4>
        <ol class="list-unstyled">
          <li><a href="#">Instagram</a></li>
          <li><a href="#">Facebook</a></li>
        </ol>
      </div>
    </div>

  </div><!-- /.row -->
  
  </main><!-- /.container -->

  {% endblock content %}

lojavirtual_v2/templates/blog/comentario.html
{% extends "blog/base_blog.html" %}
{% block post_entries %}

<form method="POST" class="post-fomr"> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save bnt bnt-default">Enviar</button>
</form>

{% endblock post_entries %}

lojavirtual_v2/templates/blog/post_destaques.html
{% extends "blog/base_blog.html" %}



{% block blog_destaques %}
{% for post in destaque_list %}
{% if forloop.first %}
<div class="p-4 p-md-5 mb-4 text-white rounded bg-destaque destaques">
<article class="blog-post-destque">
    {% if post.image %}
    <div class="row">
        <div class="col">
            <div>
                <img src="/media/{{ post.image }}" class="img-thumbnail" alt="...">
            </div>
        </div>
        <div class="col">
            <h2 class="blog-post-title">{{ post.titulo }}</h2>
            <p class="blog-post-meta" style="color: white;">{{ post.data_criado }}</p>
            <p>{{ post.texto|truncatechars:400 }}</p>
            <p><a href="{% url 'blog:post' pk=post.pk %}" style="color:white;">Continue lendo...</a></p>
        </div>
    </div>
    {% elif post.link_media %}
    <div class="row">
        <div class="col">
            <div class="embed-responsive embed-responsive-16by9">
                <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{ post.link_media }}"
                    allowfullscreen></iframe>
            </div>
        </div>
        <div class="col">
            <h2 class="blog-post-title">{{ post.titulo }}</h2>
            <p class="blog-post-meta">{{ post.data_criado }}</a></p>
            <p>{{ post.texto|truncatechars:400 }}</p>
            <p><a href="{% url 'blog:post' pk=post.pk %}">Continue lendo...</a></p>
        </div>
    </div>
    {% else %}
    <p>{{ post.texto|truncatechars:200 }}</p>
    <p><a href="{% url 'blog:post' pk=post.pk %}">Continue lendo...</a></p>
    {% endif %}
</article>
</div>
{% endif %}
{% endfor %}
{% endblock blog_destaques %}

{% block post_entries %} 
{% for post in destaque_list %}
{% if forloop.counter > 1 %}
<article class="blog-post">

    <h2 class="blog-post-title">{{ post.titulo }}</h2>
    <p class="blog-post-meta">{{ post.data_criado }}</a></p>

    {% if post.image %}
    <div class="row">
        <div class="col">
            <div>
                <img src="/media/{{ post.image }}" class="img-thumbnail" alt="...">
            </div>
        </div>
        <div class="col">
            <p>{{ post.texto|truncatechars:200 }}</p>
            <p><a href="{% url 'blog:post' pk=post.pk %}">Continue lendo...</a></p>
        </div>
    </div>
    {% elif post.link_media %}
    <div class="row">
        <div class="col">
            <div class="embed-responsive embed-responsive-16by9">
                <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{ post.link_media }}"
                    allowfullscreen></iframe>
            </div>
        </div>
        <div class="col">
            <p>{{ post.texto|truncatechars:200 }}</p>
            <p><a href="{% url 'blog:post' pk=post.pk %}">Continue lendo...</a></p>
        </div>
    </div>
    {% else %}
    <p>{{ post.texto|truncatechars:200 }}</p>
    <p><a href="{% url 'blog:post' pk=post.pk %}">Continue lendo...</a></p>
    {% endif %}

</article><!-- /.blog-post -->


{% endif %}
{% endfor %}
<a class="btn bg-destaque btn-lg btn-block" href="{% url 'blog:lista_post' %}">ver mais</a>
{% endblock post_entries %}







     

lojavirtual_v2/templates/blog/post_detail.html
{% extends "blog/base_blog.html" %}

{% block post_entries %}

<div class="post">
  <h2>{{ post.titulo }}</h2>
  <p class="meta"> {{ post.data_criado }}</p>

  {% if post.image %}
  <div style="text-align: center;">
    <img src="/media/{{ post.image }}" class="img-fluid" alt="...">
  </div>
  {% endif %}

  <p>{{ post.texto }}</p>

  {% if post.link_media %}
  <div class="embed-responsive embed-responsive-16by9">
    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{ post.link_media }}"
      allowfullscreen></iframe>
  </div>
  {% endif %}
</div>
<div class="card">
  <div class="card-body">
    <a href="{% url 'blog:comentario_novo' pk=post.pk %}">Escreva um comentário</a>
  </div>
</div>
<div id="accordion">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h5 class="mb-0">
        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true"
          aria-controls="collapseOne">
          Comentários
        </button>
      </h5>
    </div>

    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
      <div class="card-body">
        {% for comentario in object.comentario_set.all %}
        <div class="comments">
          <div class="date">
            <strong>{{comentario.autor}}</strong> - {{comentario.data_criado}}
            ({{ comentario.likes }}) <a href="{% url 'blog:comentario_like' pk=comentario.pk %}">Like</a> |
            ({{ comentario.unlikes }}) <a href="{% url 'blog:comentario_unlike' pk=comentario.pk %}">Dislike</a>
          </div>
          <p> {{ comentario.texto }}</p>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
<p style="text-align: center;">
  <a class="text-decoration-none" href="{% url 'blog:index' %}">
    Voltar
  </a>
</p>

{% endblock post_entries %}

lojavirtual_v2/templates/blog/post_list.html
{% extends "blog/base_blog.html" %}

{% block post_entries %}
{% for post in object_list %}

<article class="blog-post">

    <h2 class="blog-post-title">{{ post.titulo }}</h2>
    <p class="blog-post-meta">{{ post.data_criado }}</a></p>

    {% if post.image %}
    <div class="row">
        <div class="col">
            <div>
                <img src="/media/{{ post.image }}" class="img-thumbnail" alt="...">
            </div>
        </div>
        <div class="col">
            <p>{{ post.texto|truncatechars:200 }}</p>
            <p><a href="{% url 'blog:post' pk=post.pk %}">Continue lendo...</a></p>
        </div>
    </div>
    {% elif post.link_media %}
    <div class="row">
        <div class="col">
            <div class="embed-responsive embed-responsive-16by9">
                <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{ post.link_media }}"
                    allowfullscreen></iframe>
            </div>
        </div>
        <div class="col">
            <p>{{ post.texto|truncatechars:200 }}</p>
            <p><a href="{% url 'blog:post' pk=post.pk %}">Continue lendo...</a></p>
        </div>
    </div>
    {% else %}
    <p>{{ post.texto|truncatechars:200 }}</p>
    <p><a href="{% url 'blog:post' pk=post.pk %}">Continue lendo...</a></p>
    {% endif %}

</article><!-- /.blog-post -->
{% endfor %}

<div class="pagination">
    <span class="blog-pagination">
        {% if page_obj.has_previous %}
        <a class="btn btn-outline-primary" href="?page=1">&laquo; primeira</a>
        <a class="btn btn-outline-primary" href="?page={{ page_obj.previous_page_number }}">anterior</a>
        {% endif %}

        <!--span class="current">
            Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
        </span-->

        {% if page_obj.has_next %}
        <a class="btn btn-outline-primary" href="?page={{ page_obj.next_page_number }}">próxima</a>
        <a class="btn btn-outline-primary" href="?page={{ page_obj.paginator.num_pages }}">última &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock post_entries %}