lojavirtual_v2/blog/urls.py
from django.urls import path, re_path, include
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.BlogIndex.as_view(), name='index'),
    path('posts', views.PostList.as_view(), name='lista_post'),
    re_path(r'^post/(?P<pk>[0-9]+)$', views.BlogDetail.as_view(), name='post'),
    re_path(r'^post/(?P<pk>[0-9]+)/comentario$', views.comentario_novo, name="comentario_novo"),
    re_path(r'^comentario/(?P<pk>[0-9]+)/like$', views.comentario_like, name="comentario_like"),
    re_path(r'^comentario/(?P<pk>[0-9]+)/unlike$', views.comentario_unlike, name="comentario_unlike"),
]

lojavirtual_v2/lojavirtual/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    ##path('', include ('pages.urls')),
    ##path("cart/", include("cart.urls")),
    ##path("blog/", include("blog.urls")),
    path('', include ('products.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

lojavirtual_v2/products/urls.py
from django.urls import path, re_path

from .views import ProductDetailView, ProductListView, ProductHomeView, SaleListView, comentario_novo

app_name = "products"

urlpatterns = [
    path("", ProductHomeView.as_view(), name="home"),
    path("list", ProductListView.as_view(), name="list"),
    path("list/<slug:slug>/", ProductDetailView.as_view(), name="detail"),
    path("category/<slug:slug>/", ProductListView.as_view(), name="list_by_category"),
    path("sale/<slug:slug>/", SaleListView.as_view(), name="list_by_sale"),
    re_path(r'^list/(?P<pk>[0-9]+)/comentario$', comentario_novo, name="comentario_novo"),
]

lojavirtual_v2/products/models.py
from autoslug import AutoSlugField #instalado de terceiros
from marcador import models as app_marcador
from django.db import models
from django.urls import reverse
from model_utils.models import TimeStampedModel #instalado de terceiros (cria data de criação em alteração)


class AvailableManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_available=True)

class Category(TimeStampedModel):
    name = models.CharField(max_length=255, unique=True)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="name") #
    image = models.ImageField(upload_to="category/%Y/%m/%d", blank=True, null=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'categoria' 
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("products:list_by_category", kwargs={"slug": self.slug})


class Product(TimeStampedModel):
    category = models.ForeignKey(
        Category, related_name="products", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=255)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="name")
    image = models.ImageField(upload_to="products/%Y/%m/%d", blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    is_available = models.BooleanField(default=True)
    link_venda = models.CharField(max_length=300, null=True, blank=True)
    nota = models.IntegerField (default=0)
    likes = models.IntegerField(default=0)

    objects = models.Manager()
    available = AvailableManager()

    class Meta:
        ordering = ("-created",)
        verbose_name = 'produto'
        verbose_name_plural = 'produtos'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("products:detail", kwargs={"slug": self.slug})     

    def like (self):
        self.likes += 1  

class Comentario(TimeStampedModel):
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    autor = models.CharField(max_length=100)
    texto = models.TextField()
    likes = models.IntegerField(default=0)
    unlikes = models.IntegerField(default=0)
    data_criado = models.DateTimeField(auto_now_add=True)
    is_available = models.BooleanField(default=False)
    
    objects = models.Manager()
    available = AvailableManager()

    class Meta:
        ordering = ("-data_criado",)

    def __str__ (self):
        return self.autor + " - " + str (id)

    def like (self):
        self.likes += 1

    def unlike (self):
        self.unlikes += 1


class Images(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/%Y/%m/%d", blank=True)

    class Meta:
        verbose_name = 'imagem'
        verbose_name_plural = 'imagens'

class Sale(TimeStampedModel):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="name")
    image = models.ImageField(upload_to="sales/%Y/%m/%d", blank=True)
    is_available = models.BooleanField(default=True)

    objects = models.Manager()
    available = AvailableManager()

    class Meta:
        ordering = ('-created',)
        verbose_name = 'promoção' 
        verbose_name_plural = 'promoções'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("products:list", kwargs={"slug": self.slug})  

class Sale_Product(models.Model):
    sale = models.ForeignKey('Sale', on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    objects = models.Manager()

    class Meta:
        verbose_name = 'produtos por promoção'

class Product_Marcador(models.Model):
    marcador = models.ForeignKey(
        app_marcador.Marcador, related_name="product_marcadors", on_delete=models.CASCADE
    )
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    objects = models.Manager()

    class Meta:
        verbose_name = 'produtos por marcador'

lojavirtual_v2/products/forms.py
from django import forms
from .models import Comentario

class ComentarioForm (forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ('autor', 'texto')

lojavirtual_v2/products/views.py
#from cart.forms import CartAddProductForm
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import DetailView, ListView, TemplateView
from django.shortcuts import render
from .forms import ComentarioForm
from marcador.models import Marcador
from .models import Category, Product, Images, Sale, Sale_Product, Comentario


class ProductDetailView(DetailView):
    category = None
    #extra_context = {"form": CartAddProductForm()}
    def get_queryset(self):
        queryset = Product.available.all()
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = self.category
        context["categories"] = Category.objects.all()
        context['product_list_novidade'] = Product.available.all()[:5]
        context['comentarios'] = Comentario.available.all()
        return context


class ProductHomeView(TemplateView):
    template_name = "products/product_home.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['promocao_list'] = Sale.available.all()
        context['product_list_novidade'] = Product.available.all()[:4]
        context['product_list_preco'] = Product.objects.order_by("price")[:4]
        context['product_list_categoria'] = Product.available.all()[:2]
        context["categories"] = Category.objects.all()
        return context

class ProductListView(ListView):
    category = None
    paginate_by = 6

    def get_queryset(self):
        queryset = Product.available.all()
        category_slug = self.kwargs.get("slug")
        busca = self.request.GET.get("procurar")

        if busca:
            self.sss = Marcador.objects.filter(nome__contains = busca)
            print(self.sss)
            queryset = queryset.filter(name__contains = busca)

        if category_slug:
            self.category = get_object_or_404(Category, slug=category_slug)
            queryset = queryset.filter(category=self.category)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = self.category
        context["categories"] = Category.objects.all()
        return context

class SaleListView(TemplateView):
    template_name = "products/sale_product_list.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = Sale_Product.objects.all()
        sale_slug = self.kwargs.get("slug")
        if sale_slug:
            print(sale_slug)
            self.sale = get_object_or_404(Sale, slug=sale_slug)
            print(self.sale.id)
            queryset = queryset.filter(sale=self.sale.id)
        context['sale_list'] = queryset
        context["categories"] = Category.objects.all()
        return context

def comentario_novo (request, pk):
    product = get_object_or_404 (Product, pk=pk)
    if request.method == 'POST':
        form = ComentarioForm (request.POST)
        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.product = product
            comentario.save()
            return redirect (reverse ('products:detail', kwargs={'slug': product.slug}))
    else:
        form = ComentarioForm()
    return render (request, 'products/comentario.html', {'form': form})

lojavirtual_v2/templates/products/comentario.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<form method="POST" class="post-fomr"> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save bnt bnt-default">Enviar</button>
</form>
</div>

{% endblock content %}

lojavirtual_v2/templates/products/product_detail.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/product_datail.css' %}" />
{% endblock css %}

{% block title %}- {{ product.name }}{% endblock title %}

{% block content %}

<div class="container my-3">
  <div class="row">
    <div class="col-lg-7 mb-3 mb-lg-0">
      {% if product.image %}
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          {% for image in object.images_set.all %}
          <li data-target="#carouselExampleIndicators" data-slide-to="{{image.id}}" {% if forloop.first %}
            class="active" {% endif %}></li>
          {% endfor %}
        </ol>
        <div class="carousel-inner">
          {% for image in object.images_set.all %}
          <div class="carousel-item {% if forloop.first %} active {% endif %}">
            <img src="/media/{{image.image}}" class="center" alt="...">
          </div>
          {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
      {% else %}
      <img class="card-img-top" src="{% static 'images/no_image.jpg' %}" alt="">
      {% endif %}
    </div>
    <div class="col-lg-5">
      <h1 class="font-weight-bold">{{ product.name }}</h1>
      <h2>R$ {{ product.price }}</h2>
      <h3 style="color: green;">Estoque disponível</h3>
      <h4>Quantidade em estoque: 1 und.</h4>

      {% if product.link_venda %}
      <a href="{{ product.link_venda }}" target="blank"><span class="badge badge-success"
          style="font-size: 200%;">COMPRAR</span></a>
      {% endif %}
      <p>
        
        <a class="text-decoration-none" href="{{ product.category.get_absolute_url }}">
          Encontre mais produtos semelhantes.
        </a>
      </p>
    </div>
  </div>
  <div style="padding-top: 2%;">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Descricão</h5>
        <p class="card-text">{{ product.description }}</p>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-body">
      <a href="{% url 'products:comentario_novo' pk=product.pk %}">Deixe seu comentário</a>
    </div>
  </div>
  <div id="accordion">
    <div class="card">
      <div class="card-header" id="headingOne">
        <h5 class="mb-0">
          <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true"
            aria-controls="collapseOne">
            Comentários 
            <i class="bi-chevron-compact-down" role="img" aria-label="chevron-compact-down"></i>
          </button>
        </h5>
      </div>

      <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
        <div class="card-body">
          {% for comentario in object.comentario_set.all %}
          <div class="comments">
            <div class="date">
              <strong>{{comentario.autor}}</strong> <small class="text-muted">- {{comentario.data_criado}}</small>
            </div>
            <p> {{ comentario.texto }}</p>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

  <!--Destques-->
  <div class="container">
    <div class="card-deck">
      {% for product in product_list_novidade %}
      <div class="card">
        <a href="{{ product.get_absolute_url }}">
          {% if product.image %}
          <img class="card-img-top" src="/media/{{product.image}}" alt="">
          {% else %}
          <img class="card-img-top" src="{% static 'images/no_image.jpg' %}" alt="">
          {% endif %}
        </a>
        <div class="card-body d-flex flex-column justify-content-between">
          <a class="text-decoration-none text-dark" href="{{ product.get_absolute_url }}">
            <h5 class="card-title">{{ product.name }}</h5>
          </a>
        </div>
      </div>

      {% endfor %}

    </div>
  </div>
</div>

{% endblock content %}

lojavirtual_v2/templates/products/product_home.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/loja.css' %}">
<link rel="stylesheet" href="{% static 'css/carousel_cards.css' %}">
{% endblock css %}



{% block content %}



<div class="container">
    <!--Promoções-->
    <div class="promocao">
        <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
            <div class="carousel-inner">
                {% for  product in promocao_list %}
                <div class="carousel-item {% if forloop.first %} active {% endif %}">
                    <a href="sale/{{ product.slug }}">
                        <img src="/media/{{product.image}}" class="img-fluid" alt="..." style="height: 50vh;width: 100%;">
                    </a>
                </div>
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <!--Destques-->
    <div class="container">
      <h2>Destaques</h2>
        <div class="card-deck">
            {% for product in product_list_novidade %}
            <div class="card">
              <a href="{{ product.get_absolute_url }}">
                {% if product.image %}
                <img class="card-img-top" src="/media/{{product.image}}" alt="">
                {% else %}
                <img class="card-img-top" src="{% static 'images/no_image.jpg' %}" alt="">
                {% endif %}
              </a>
              <div class="card-body d-flex flex-column justify-content-between">
                <a class="text-decoration-none text-dark" href="{{ product.get_absolute_url }}">
                  <h5 class="card-title">{{ product.name }}</h5>
                  <p class="card-text">R${{ product.price }}</p>
                  <!--p class="card-text">{{ product.description|truncatechars:50  }}</p-->
                </a>
              </div>
            </div>
            {% endfor %}
          </div>
    </div>
    <!--Categoira>
    <div class="container">
        <div class="row detalhes categoria_destaque"">
            {% for  product in product_list_categoria %}
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row no-gutters">
                  <div class="col-md-4">
                    <img src="/media/{{product.image}}" class="card-img-top" alt="...">
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                    <a href="{{ product.get_absolute_url }}" style="color: black;">
                      <h5 class="card-title">{{ product.name }}</h5>
                      <p class="card-text">R${{ product.price }}</p>
                    </a>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
        </div>
    </div-->
    
    <!--Preço-->
    <div class="container">
      <h2>Melhor preço</h2>
        <div class="card-deck">
            {% for product in product_list_preco %}
            <div class="card">
              <a href="{{ product.get_absolute_url }}">
                {% if product.image %}
                <img class="card-img-top" src="/media/{{product.image}}" alt="">
                {% else %}
                <img class="card-img-top" src="{% static 'images/no_image.jpg' %}" alt="">
                {% endif %}
              </a>
              <div class="card-body d-flex flex-column justify-content-between">
                <a class="text-decoration-none text-dark" href="{{ product.get_absolute_url }}">
                  <h5 class="card-title">{{ product.name }}</h5>
                  <p class="card-text">R${{ product.price }}</p>
                  <!--p class="card-text">{{ product.description|truncatechars:50  }}</p-->
                </a>
              </div>
            </div>
            {% endfor %}
          </div>
    </div>

</div>
{% endblock content %}

{% block scripts %}
<script src="{% static 'js/carousel_cards.js' %}"></script>
{% endblock scripts %}

lojavirtual_v2/templates/products/product_list.html
{% extends 'base.html' %}

{% load static %}
{% load product_tags %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/product_list.css' %}">
{% endblock css %}

{% block title %}
{% if category %}
- {{ category.name }}
{% else %}
- Produtos
{% endif %}
{% endblock title %}

{% block content %}

<div class="container my-3">
    <div class="row">
        <div class="col"> {% if product_list %}
            {%if product_list.count < 8 %}
            <!-- menos de 8 produtos -->

            <div class="row detalhes categoria_destaque"">
            {% for  product in product_list %}
            <div class=" card mb-2" style="max-width: 48%; margin: 1%;">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="/media/{{product.image}}" class="card-img-top" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <a href="{{ product.get_absolute_url }}" style="color: black;">
                                <h5 class="card-title">{{ product.name }}</h5>
                                <p class="card-text">{{ product.description|truncatechars:50  }}</p>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}


        {%if product_list.count > 7 %}
        <!-- mais de 7 produtos -->
        <div class="card-deck">
            {% for product in product_list %}
            <div class="card">
                <a href="{{ product.get_absolute_url }}">
                    {% if product.image %}
                    <img class="card-img-top" src="/media/{{product.image}}" alt="">
                    {% else %}
                    <img class="card-img-top" src="{% static 'images/no_image.jpg' %}" alt="">
                    {% endif %}
                </a>
                <div class="card-body d-flex flex-column justify-content-between">
                    <a class="text-decoration-none text-dark" href="{{ product.get_absolute_url }}">
                        <h5 class="card-title">{{ product.name }}</h5>
                    </a>
                    <a class="text-decoration-none text-dark" href="{{ product.get_absolute_url }}">
                        <p class="card-text font-weight-bold">R$ {{ product.price }}</p>
                    </a>
                </div>
            </div>
            {% if forloop.counter|divisibleby:"4" and not forloop.last %}

        </div>
        <div class="card-deck">
            {% endif %}
            {% endfor %}

            {% if product_list|length|remainder == 3 %}
            <div class="card border-0" style="background-color: #E6E6FA"></div>
            {% elif product_list|length|remainder == 2 %}
            <div class="card border-0" style="background-color: #E6E6FA"></div>
            <div class="card border-0" style="background-color: #E6E6FA"></div>
            {% elif product_list|length|remainder == 1 %}
            <div class="card border-0" style="background-color: #E6E6FA"></div>
            <div class="card border-0" style="background-color: #E6E6FA"></div>
            <div class="card border-0" style="background-color: #E6E6FA"></div>
            {% endif %}
        </div>
        {% endif %}

        {% if is_paginated %}
        {% include "pagination.html" with page=page_obj %}
        {% endif %}
        {% else %}
        <p>Nenhum produto encontrado.</p>
        {% endif %}
    </div>
</div>
</div>

{% endblock content %}

lojavirtual_v2/templates/products/sale_product_list.html
{% extends 'base.html' %}

{% load static %}
{% load product_tags %}

{% block title %}
{% if category %}
{{ category.name }}
{% else %}
Produtos
{% endif %}
{% endblock title %}

{% block content %}

<div class="container my-3">
    <div class="row">
        <div class="col-lg-3">
            <ul class="list-group mb-3 mb-lg-0">
                <a class="text-decoration-none list-group-item list-group-item-light {% if not category %}active{% endif %}"
                    href="{% url 'products:list' %}">
                    Todos os produtos
                </a>

                {% for cat in categories %}
                <a class="text-decoration-none list-group-item list-group-item-light {% if category == cat %}active{% endif %}"
                    href="{{ cat.get_absolute_url }}">
                    {{ cat.name }}
                </a>
                {% endfor %}
            </ul>
        </div>
        <div class="col-lg-9">
            <div class="card-deck mb-3">
                {% for sale in sale_list %}
                <div class="card">
                    <a href="{{ sale.product.get_absolute_url }}">
                        {% if sale.product.image %}
                        <img class="card-img-top" src="/media/{{sale.product.image}}" alt="">
                        {% else %}
                        <img class="card-img-top" src="{% static 'images/no_image.jpg' %}" alt="">
                        {% endif %}
                    </a>

                    <div class="card-body d-flex flex-column justify-content-between">
                        <a class="text-decoration-none text-dark" href="{{ sale.product.get_absolute_url }}">
                            <h5 class="card-title">{{ sale.product.name }}</h5>
                        </a>
                        <a class="text-decoration-none text-dark" href="{{ product.get_absolute_url }}">
                            <p class="card-text font-weight-bold">R$ {{ sale.product.price }}</p>
                        </a>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:"3" and not forloop.last %}
            </div>
            <div class="card-deck mb-3">
                {% endif %}
                {% endfor %}

                {% if sale_list|length|remainder == 2 %}
                <div class="card border-0"></div>
                {% elif sale_list|length|remainder == 1 %}
                <div class="card border-0"></div>
                <div class="card border-0"></div>
                {% endif %}
            </div>

            {% if is_paginated %}
            {% include "pagination.html" with page=page_obj %}
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}